### Imports.
---

In [1]:
import numpy as np
import pandas as pd

### Version Confirmation.
---

In [2]:
print(np.version.version)

1.26.4


In [3]:
print(pd.__version__)

2.2.3


### Salutions.
---

In [4]:
print('Hello HCIA PDTP-Huawei Team')

Hello HCIA PDTP-Huawei Team


### Two Variables Program.
---

In [5]:
var1= 23
var2 = 76
print(var1 + var2)

99


### Tuple Questions.
---

In [6]:
tuple_1= ('Maxy')
print(tuple_1)

Maxy


In [7]:
tuple_2 = (234, "MAX", "Justus", 'Ben')
for i in tuple_2:
    print("Tuple content", i)

Tuple content 234
Tuple content MAX
Tuple content Justus
Tuple content Ben


### Dictionary Exercise.
---

In [8]:
dict_2 ={ "name":"Reagan", "Phone_number":"+254 722 222333"}
for key in dict_2:
    print(key)
for key in dict_2:
    print(dict_2[key])

name
Phone_number
Reagan
+254 722 222333


In [9]:
dict_1 ={ "name":"Reagan", "Phone_number":"+254 722 222333"}
print('Phone Number Owner and details', dict_1)

Phone Number Owner and details {'name': 'Reagan', 'Phone_number': '+254 722 222333'}


### Multiplication.
----

In [10]:
def multiply(x,y):
    return print(x*y)
multiply(8,6)

48


In [11]:
def sqrprod(x,y):
    return print((x*y)*(y*x))
sqrprod(2,5)

100


### Numpy Tasks.
---

In [12]:
array_1 = np.full((5,5),0)
print(array_1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
indices = np.array([1,2,0,0,4,0])

non_zero = np.nonzero(indices)

print(non_zero)

(array([0, 1, 4], dtype=int64),)


In [17]:
indices = [1,2,0,0,4,0]
non_zero_2 = []
for i in range(len(indices)):
    if indices[i] != 0:
        non_zero_2.append(i)
        
    print (non_zero_2)

[0]
[0, 1]
[0, 1]
[0, 1]
[0, 1, 4]
[0, 1, 4]


In [21]:
array_3 = np.random.rand(10,10)
print(array_3)

small = np.min(array_3)
print(small)

[[0.44660433 0.47406933 0.46400039 0.23229988 0.00459622 0.24862274
  0.82785491 0.14627357 0.87167493 0.48347429]
 [0.10897267 0.80597214 0.66719492 0.68298392 0.01459506 0.18539244
  0.93541128 0.63809673 0.6520369  0.54394868]
 [0.8494073  0.33111741 0.37241278 0.26905546 0.24971051 0.89946041
  0.68231232 0.96867669 0.95538143 0.40186176]
 [0.53796832 0.80906546 0.31853745 0.71598329 0.84091718 0.02866884
  0.28891508 0.35065957 0.12731755 0.81573023]
 [0.98723215 0.63875706 0.01399946 0.755281   0.74651022 0.19011017
  0.71855637 0.19856369 0.23820332 0.95409708]
 [0.15414128 0.61450036 0.72069926 0.72698753 0.97268453 0.00427878
  0.61260193 0.91944842 0.5864368  0.65827662]
 [0.35920981 0.77704909 0.00398005 0.18172802 0.20357992 0.71672637
  0.7226214  0.37895678 0.73832119 0.79262513]
 [0.98038383 0.45944705 0.61467679 0.34101045 0.25831974 0.24690443
  0.04922141 0.80204471 0.49706667 0.1730085 ]
 [0.1105869  0.89217582 0.41528504 0.381654   0.69664405 0.8570555
  0.50797155 