In [1]:
import mindspore
import numpy as np
from mindspore import Tensor
from mindspore import dtype

In [2]:
x = Tensor(np.array([[1,2],[3,4]]), dtype.int32)
x

Tensor(shape=[2, 2], dtype=Int32, value=
[[1, 2],
 [3, 4]])

### Create tensors using numbers.
---

In [3]:
y = Tensor(1.0, dtype.int32)
z = Tensor(2, dtype.int32)
y
z

Tensor(shape=[], dtype=Int32, value= 2)

### Create a tensor using Boolean.
---

In [4]:
m = Tensor(True, dtype.bool_)
m

Tensor(shape=[], dtype=Bool, value= True)

### Create a tensor using Tuple.
---

In [5]:
n = Tensor((1, 2, 3), dtype.int16)
n

Tensor(shape=[3], dtype=Int16, value= [1, 2, 3])

### Create a tensor using a List.
---

In [6]:
p = Tensor([4.0, 5.0, 6.0], dtype.float64)
p

Tensor(shape=[3], dtype=Float64, value= [ 4.00000000e+00,  5.00000000e+00,  6.00000000e+00])

#### Inherit attributes of another tensor to form a new tensor.
---

In [7]:
from mindspore import ops
oneslike = ops.OnesLike()
x = Tensor(np.array([[0, 1], [2, 1]]).astype(np.int32))
output = oneslike(x)
output

Tensor(shape=[2, 2], dtype=Int32, value=
[[1, 1],
 [1, 1]])

#### Output constant tensor value.
---

In [8]:
from mindspore.ops import operations as ops
shape = (2, 2)
ones = ops.Ones()
output = ones(shape,dtype.float32)
print(output)
zeros = ops.Zeros()
output = zeros(shape, dtype.float32)
print(output)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


### Tensor Attributes.
---

In [10]:
x = Tensor(np.array([[1, 2], [3, 4]]), dtype.int32)

x.size # Size

4

In [13]:
x.shape # Shape


(2, 2)

In [12]:
x.ndim

2

In [14]:
x.dtype # Data type

mindspore.int32

### Tensor Methods.
---

In [15]:
y = Tensor(np.array([[True, True], [False, False]]), dtype.bool_)
# Convert the tensor data type to NumPy.
y_array = y.asnumpy()
y
y_array

array([[ True,  True],
       [False, False]])

### Tensor Operations.
---

In [16]:
tensor = Tensor(np.array([[0,1],[2,3]]).astype(np.float32))
print("First row: {}".format(tensor[0]))
print("First column: {}".format(tensor[:, 0]))
print("Last column: {}".format(tensor[..., -1]))


First row: [0. 1.]
First column: [0. 2.]
Last column: [1. 3.]


### Concatenate Tensors.
---

In [17]:
data1 = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
data2 = Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))
op = ops.Stack()
output = op([data1, data2])
print(output)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


### Convert to NumPy.
---

In [18]:
zeros = ops.Zeros()
output = zeros((2,2), dtype.float32)
print("output: {}".format(type(output)))
n_output = output.asnumpy()
print("n_output: {}".format(type(n_output)))

output: <class 'mindspore.common._stub_tensor.StubTensor'>
n_output: <class 'numpy.ndarray'>
